### ISSUE TITLE
what type is a surrogate model (does it need to be its own class?)

### ISSUE THREAD

**Issue by SashaSaw** [SashaSaw/SAMOTA-Lib#2]
@donghwan-shin trainLocal and trainGlobal return surrogate models what type is a surrogate model (does it need to be its own class?) i guess it could maybe have a parent class surrogate model and then have multiple types of surrogate model children (allows user to code their own child of this class).
https://github.com/SashaSaw/SAMOTA-Lib/blob/c5bc9174ad2f125b570aec91665ccee8017e93c9/LocalSearch.py#L23
https://github.com/SashaSaw/SAMOTA-Lib/blob/c5bc9174ad2f125b570aec91665ccee8017e93c9/GlobalSearch.py#L16

**Comment by donghwan-shin** [comment]
Yes, that sounds sensible. The common functions for the SurrogateModel instances should be: train() and predict().
