### ISSUE TITLE
what does calcFitnessLS do and is updateBestPredicted correctly described?

### ISSUE THREAD

**Issue by SashaSaw** [SashaSaw/SAMOTA-Lib#3]
@donghwan-shin in the meeting maybe I would like to discuss what calcFitnessLS does and make sure i understand updateBestPredicted correctly.
https://github.com/SashaSaw/SAMOTA-Lib/blob/c5bc9174ad2f125b570aec91665ccee8017e93c9/LocalSearch.py#L30-L39

**Comment by donghwan-shin** [comment]
`calcFitnessLS()` just calculates the (predicted) fitness scores of the given test cases using the given local surrogate model. 

Yes, the description of `updateBestPredicted()` looks correct.
