### ISSUE TITLE
what does generateNextGen do?

### ISSUE THREAD

**Issue by SashaSaw** [SashaSaw/SAMOTA-Lib#4]
@donghwan-shin (the paper only says generate the next generation 𝑃 from 𝑊 for 𝑈) i dont get what it means by for 𝑈 though?
https://github.com/SashaSaw/SAMOTA-Lib/blob/c5bc9174ad2f125b570aec91665ccee8017e93c9/Search.py#L17-L22

**Comment by donghwan-shin** [comment]
<img width="469" alt="image" src="https://github.com/SashaSaw/SAMOTA-Lib/assets/12538465/f68dc5bc-e94a-4e4c-a527-f63e6799569d">

As explained in the paper (above), `generateNextGen()` is essentially the "selection" in GA. You could implement **Tournament Selection**, one of the widely used selection techniques (see the "Essentials of Metaheuristics" book for more details). When `U` is a parameter, it means the function aims to reduce the population size (i.e., the number of test cases in the next generation) to `|U|`. 

<img width="585" alt="image" src="https://github.com/SashaSaw/SAMOTA-Lib/assets/12538465/2679291a-8d70-4eac-b491-3ac06e3ddc32">
