### ISSUE TITLE
What type are objectives?

### ISSUE THREAD

**Issue by SashaSaw** [SashaSaw/SAMOTA-Lib#5]
@donghwan-shin  A lot of the functions take a set of objectives to actually check whether test cases achieve them and so variable like uncovered objectives cant just be integer types, but then what type should they be and do they perhaps also need to be their own class?
https://github.com/SashaSaw/SAMOTA-Lib/blob/c5bc9174ad2f125b570aec91665ccee8017e93c9/GlobalSearch.py#L34-L46
for example here if uncovered_objects is just an integer variable how could the program check for the best test cases for each objective?

**Comment by donghwan-shin** [comment]
An objective is "achieved" when the corresponding fitness score (calculated by the sim) is higher than the corresponding threshold. 

For example, we could have the following variables:
```python
num_objectives = 5
thresholds = [0.9, 0.7, 0.9, 1, 1] # threshold[i] is the threshold for the ith objective; should be initialised by the user for a given problem
uncovered_obj_indexes = {0, 1, 2, 3, 4} # meaning all five objectives are uncovered
```

Later, we could execute `uncovered_obj_indexes.remove(i)` when `fitness_score[i] >= threshold[i]` for a newly created test case.
